name: 🐞 Bug Report
description: File a bug report to help us improve the bot
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: 📋 Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔁 Steps to Reproduce
      description: Explain how to reproduce the issue step by step.
      placeholder: |
        1. Run command '...'
        2. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📸 Screenshots / Logs
      description: If applicable, add screenshots or paste console errors.
      render: shell

  - type: input
    id: environment
    attributes:
      label: 💻 Environment
      description: OS, Node.js version, Discord.js version, hosting method
      placeholder: "Windows 11, Node.js 20.x, discord.js 14.x, Railway"
